// <auto-generated />
using System;
using Haver_Boecker_Niagara.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Haver_Boecker_Niagara.Migrations.Haver
{
    [DbContext(typeof(HaverContext))]
    [Migration("20250118214129_FixRelationships")]
    partial class FixRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.ApprovalDrawing", b =>
                {
                    b.Property<int>("DrawingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrawingID");

                    b.HasIndex("OrderID");

                    b.ToTable("ApprovalDrawings");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.BOM", b =>
                {
                    b.Property<int>("BOM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BOM_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("BOM_Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BOM_ID");

                    b.HasIndex("OrderID");

                    b.ToTable("BOMs");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Engineer", b =>
                {
                    b.Property<int>("EngineerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EngineerID");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.GanttSchedule", b =>
                {
                    b.Property<int>("GanttID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerID1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineerID1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PromiseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GanttID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("CustomerID1");

                    b.HasIndex("EngineerID");

                    b.HasIndex("EngineerID1");

                    b.ToTable("GanttSchedules");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.KickoffMeeting", b =>
                {
                    b.Property<int>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyDiscussions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingID");

                    b.HasIndex("OrderID");

                    b.ToTable("KickoffMeetings");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Milestone", b =>
                {
                    b.Property<int>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("MilestoneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MilestoneID");

                    b.HasIndex("OrderID");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.NCR", b =>
                {
                    b.Property<int>("NCR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateIssued")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NCR_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NCR_ID");

                    b.HasIndex("OrderID");

                    b.ToTable("NCRs");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.OperationsSchedule", b =>
                {
                    b.Property<int>("OperationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirSeal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoatingOrLining")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disassembly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PODueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PackageReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SparePartsMedia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendorID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationsID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("VendorID");

                    b.HasIndex("VendorID1");

                    b.ToTable("OperationsSchedules");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.ProgressLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DoneFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LateFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.HasIndex("OrderID");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VendorID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.ApprovalDrawing", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.BOM", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.GanttSchedule", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haver_Boecker_Niagara.Models.Customer", null)
                        .WithMany("GanttSchedules")
                        .HasForeignKey("CustomerID1");

                    b.HasOne("Haver_Boecker_Niagara.Models.Engineer", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haver_Boecker_Niagara.Models.Engineer", null)
                        .WithMany("GanttSchedules")
                        .HasForeignKey("EngineerID1");

                    b.Navigation("Customer");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.KickoffMeeting", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Milestone", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.NCR", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.OperationsSchedule", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.Customer", "Customer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haver_Boecker_Niagara.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haver_Boecker_Niagara.Models.Vendor", null)
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("VendorID1");

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.ProgressLog", b =>
                {
                    b.HasOne("Haver_Boecker_Niagara.Models.GanttSchedule", "GanttSchedule")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GanttSchedule");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Customer", b =>
                {
                    b.Navigation("GanttSchedules");

                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Engineer", b =>
                {
                    b.Navigation("GanttSchedules");
                });

            modelBuilder.Entity("Haver_Boecker_Niagara.Models.Vendor", b =>
                {
                    b.Navigation("OperationsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
